{
  "name": "module6_Exception_Try_1",
  "description": "Exception Try Catch 1",
  "main": "Main.xaml",
  "dependencies": {},
  "excludedData": [
    "Private:*",
    "*password*"
  ],
  "toolVersion": "18.2",
  "projectVersion": "1.0.6808.19545",
  "packOptions": {},
  "runtimeOptions": {}
}